name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: alekxaguilar/ta-ci-web-taf/.github/workflows/auto-build.yml@main

  release-tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Automation Tests - Release health check
        run: echo Automation project built

  results:
    needs: [release-tests]
    uses: alekxaguilar/ta-ci-web-taf/.github/workflows/auto-testresults.yml@main
