name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:
  reporting:
    needs: [auto-verification]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Reporting
        run: echo Collecting results and notifying
