name: CI
on:
  workflow_dispatch:
  workflow_call:

jobs:
  notifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Reporting
        run: echo Collecting results and notifying
