# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-taf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Automation projet image
        run: echo Automation project built
  auto-verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Automation Tests - Release health check
        run: echo Automation project built
  reporting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Reporting
        run: echo Collecting results and notifying
