name: CI
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-taf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Automation projet image
        run: echo Automation project built        
